packages:
  - app/*
  - packages/*
  - tests/*
  - examples/*

catalog:
  '@types/node': 25.9.5
  effect: 4.0.0-beta.65
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8

overrides:
  '@effect/platform-node-shared': 4.0.0-beta.65
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8

allowBuilds:
  esbuild: true
  msgpackr-extract: true
